#
# This file is part of Becoming a Hacker Foundations
# Copyright (c) 2024, Cisco Systems, Inc.
# All rights reserved.
#

#
# This is the configuration file for the Foundations lab environment.
#

pod_count: 4
pod_domain_name: pod.becomingahacker.com

# Becoming a Hacker Load Balancer FQDN
lb_fqdn: becomingahacker.com
domain_name: becomingahacker.com

gcp:
  # Must be globally unique and updated in terraform.tf backend config
  tfstate-bucket: bah-cml-terraform-state
  tfstate-key: "bah-foundations-lab/state"
  # Path to JSON-formatted service account key file.  Not required if using
  # gcloud auth application-default login  Leave empty in this case.
  credentials:
  project: gcp-asigbahgcp-nprd-47930
  region: asia-south1
  zone: asia-south1-a
  bucket: bah-machine-images
  ## Machines will inherit the SSH keys from project's metadata for all users unless you provide below
  ## <user>:<ssh public key>
  ## e.g. ssh_keys: "cml:ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGDAqIBESzn9J9rdSLarhyU6GNycV+43DkdkNzSgfLrP"
  ## HACK cmm - the Catalyst 8000v doesn't use project-level metadata.  It needs explicit keys.
  #ssh_keys: |
  #  stieng:ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHCgsKQbtqJBMB1fDhwyuI1IDJYf2mfkVADmwfvuXqpt stieng@cisco.com
  #  bootstrap_ssh_ed25519:ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGDAqIBESzn9J9rdSLarhyU6GNycV+43DkdkNzSgfLrP bootstrap_ssh_ed25519
  #  cmm:ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMgtVIy38RA7DneT3dZHXMbZx13lCOBpWetiFSlZp/9s cmm@cisco.com
  #  evstiles:ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFqxtqPw1G8p9y1B0baapoNLnt1owrr3UpRfLFEBuddx evstiles@cisco.com
  #  nweigand:ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKh/PoDlHZ784blTY39txDUsQaI6nzdE53CjngwYM5MD nweigand@cisco.com
  #  jallbrit:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJX9lBCF2q+wkZviWilVjN7tPxja7wLYowfS8UncpkGITkPVnXcRPZzX4xeJVvoCCSjNuR+tdE7bQluMogrzZ9kKwW7vtzq95OYPbsZsOXEo9apzha2pMhQnVQWuUrME+v46TNo6jI2VGYgCV9J8puoQCTIimE0kZi2FT8/f2Qu6h/wNm3mWKsCUoZbtWK3NBrrYGpvgJkFCccJSnl7aTdOvem1PKbqg492vh4MI7ejPyBrOLGTF0oxFneLtXk0sPG8nTee0vzJrr930bS0lm77GSv+DPMiZ+De1zFGOqK6uPmLUUhfCfAMEXhghcZNKJmcmw9Jl290tqi8NMmlFp7XJ9TGXLiU1HpimRBMshkmUpdfxOwUZgVuON3yJ7KsxHKf1IfEcT1O3uDkjDOTB73NGoAu0tAJFqF9vZmxFMvp/aL1eje+ysLpqT+pBUueR55IWrmaQkOeO4Hxp/uMkX6EqLL4FP/Tsm87gkJaGGBs2/gv5cMC5E+a6K88afzk00= jallbrit@cisco.com
  dns_zone_name: becomingahacker-com

# FIXME cmm - No longer used
c8k:
  instance_count: 2
  # gcloud compute images list --project cisco-public
  # gcloud compute images create cisco-c8k-17-16-01a --source-image projects/cisco-public/global/images/cisco-c8k-17-16-01a
  image: cisco-c8k-17-16-01a
  machine_type: n1-standard-2
  disk_size_gb: 16
  hostname_prefix: bah-c8k
  network_name: cml-c8k-network
  subnet_name: bahf-c8k-subnet
  subnet_cidr: 10.64.2.0/24
  # The loopback IP address prefix for the Catalyst 8000v instances.  Uses the last IPs first to make room
  # for pod loopback addresses
  loopback_ipv4_prefix: 10.64.0.0/24
  service_account_id: bah-foundations
  service_account_display_name: "Becoming a Hacker Foundations Pod Service Account"
  allowed_ipv4_subnets:
    ## GCE cml-subnet
    #- "10.10.0.0/16"
    ## GCE Health Chekers
    #- "35.191.0.0/16"
    #- "209.85.152.0/22"
    #- "209.85.204.0/22"
    ## Google Front End
    #- "34.96.0.0/16"
    #- "34.127.0.0/16"
    # RTP NAT pool
    - "173.38.117.64/26"
    # cmm
    - "23.116.118.232/29"
    # cmm
    - "99.69.22.234/32"
    # ASIG
    - "64.100.197.0/24"
    - "64.100.220.0/23"

cml:
  # WARNING: These may all need to be updated to match deployment
  network_name: cml-network-55267dbe
  subnet_name: cml-controller-subnet-55267dbe
  lab_network_endpoint_group_self_link: "https://www.googleapis.com/compute/v1/projects/gcp-asigbahgcp-nprd-47930/zones/asia-south1-a/networkEndpointGroups/cml-controller-lab-neg-55267dbe"
  bgp_ipv6_peer: "2600:1900:40a0:4de::1:ffff"

secret:
  # At this time, 'vault', 'conjur' and 'dummy' are supported secrets managers.
  # Make sure that you also run the prepare.sh / prepare.bat script, otherwise
  # a 'raw_secret' will be used.  If 'raw_secret' is not defined, a random
  # password will be used.
  # https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password
  #manager: vault
  manager: conjur
  #manager: dummy

  conjur:

  vault:
    # Only the v2 version of the key value secret engine is supported
    # https://developer.hashicorp.com/vault/docs/secrets/kv/kv-v2
    kv_secret_v2_mount: secret
    # Set this to true to prevent the creation of ephemeral child token used by this provider.
    skip_child_token: true

  # These are the secrets that will be used by the CML instances.  This key
  # gets mapped to the main configuration under 'secrets'.  The values are
  # filled in by the secrets manager and are accessible using the 'secret'. For
  # example, the 'app' password is accessed using 'secrets.app.secret'. The
  # SmartLicense token is accessed using 'secrets.smartlicense_token.secret'.
  secrets:
    app:
      username: admin
      # Used with dummy secret manager.  If unspecified, a random password will
      # be generated. You need to escape special chars:
      #raw_secret: '\"!@$%'
      #raw_secret: your-secret-password
      # Path to secret, used with both Vault and Conjur:
      path: sto/becomingahacker/secret/common/becomingahacker.com/prod/host/cml-0.becomingahacker.com/admin_password
      # Used with Vault only:
      #field: secret

