#
# This file is part of Becoming a Hacker Foundations
# Copyright (c) 2024, Cisco Systems, Inc.
# All rights reserved.
#

#
# This is the configuration file for the Foundations lab environment.
#

# Becoming a Hacker Load Balancer FQDN
lb_fqdn: becomingahacker.com

domain_name: becomingahacker.com

secrets:
  - &app_password  sto/becomingahacker/secret/common/becomingahacker.com/prod/host/cml-0.becomingahacker.com/admin_password

app:
  user: admin
  pass: *app_password

pod_count: 20
